[package]
name = "genalgo_engine"
version = "0.1.0"
authors = ["John <john@sparta>"]
edition = "2018"

[lib]
name = "genalgo_engine"
crate-type = ["cdylib"]

[dependencies]
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0"
log = "0.4.11"
rand = "0.8.3"
rand_distr = "0.4.0"
